### ISSUE TITLE
Move to JuliaMath?

### ISSUE THREAD

**Issue by jiahao** [JuliaMath/RandomMatrices.jl#27]
@JuliaMath @dlfivefifty 

This package started out as my very first Julia code, but it's no longer fair for me to continue owning the repository now that @dlfivefifty @andreasnoack and others have been contributing all sorts of useful bits of code.

**Comment by dlfivefifty** [comment]
👍🏽

**Comment by dlfivefifty** [comment]
Or JuliaStats?  There's currently nothing probability related in JuliaMath, where JuliaStats contains the related Distributions.jl package.

**Comment by dlfivefifty** [comment]
Or JuliaStats?  There's currently nothing probability related in JuliaMath, where JuliaStats contains the related Distributions.jl package.

**Comment by jiahao** [comment]
@JuliaStats is another possibility
