### ISSUE TITLE
Please catch up with the Julia version

### ISSUE THREAD

**Issue by algorithmx** [JuliaMath/RandomMatrices.jl#32]
Julia version:

================================================
XXX@XXX $ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.1 (2017-10-24 22:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> 
================================================
Precompile Warnings:

WARNING: deprecated syntax "typealias Dim2 Tuple{Int,Int}" at /home/yunlong/.julia/v0.6/RandomMatrices/src/RandomMatrices.jl:23.
Use "const Dim2 = Tuple{Int,Int}" instead.
INFO: 
Precompiling module Combinatorics.
INFO: Precompiling module GSL.
INFO: Precompiling module ODE.
INFO: Precompiling module Distributions.

WARNING: deprecated syntax "typealias Wigner{β} GaussianHermite{β}" at /home/yunlong/.julia/v0.6/RandomMatrices/src/GaussianEnsembles.jl:49.
Use "Wigner{β} = GaussianHermite{β}" instead.

WARNING: deprecated syntax "typealias Wishart GaussianLaguerre" at /home/yunlong/.julia/v0.6/RandomMatrices/src/GaussianEnsembles.jl:151.
Use "const Wishart = GaussianLaguerre" instead.

WARNING: deprecated syntax "typealias MANOVA GaussianJacobi" at /home/yunlong/.julia/v0.6/RandomMatrices/src/GaussianEnsembles.jl:225.
Use "const MANOVA = GaussianJacobi" instead.

WARNING: deprecated syntax "inner constructor Semicircle(...) around /home/yunlong/.julia/v0.6/RandomMatrices/src/densities/Semicircle.jl:12".
Use "Semicircle{T}(...) where T" instead.

WARNING: deprecated syntax "typealias partition Vector{Int}" at /home/yunlong/.julia/v0.6/RandomMatrices/src/Haar.jl:6.
Use "const partition = Vector{Int}" instead.

WARNING: deprecated syntax "inner constructor FormalPowerSeries(...) around /home/yunlong/.julia/v0.6/RandomMatrices/src/FormalPowerSeries.jl:22".
Use "FormalPowerSeries{#s61}(...) where #s61" instead.

WARNING: deprecated syntax "inner constructor FormalPowerSeries(...) around /home/yunlong/.julia/v0.6/RandomMatrices/src/FormalPowerSeries.jl:24".
Use "FormalPowerSeries{#s60}(...) where #s60" instead.

WARNING: deprecated syntax "function .*(...)".
Use "function Base.broadcast(::typeof(*), ...)" instead.

WARNING: deprecated syntax "inner constructor FormalLaurentSeries(...) around /home/yunlong/.julia/v0.6/RandomMatrices/src/FormalPowerSeries.jl:298".
Use "FormalLaurentSeries{#s61}(...) where #s61" instead.

WARNING: deprecated syntax "inner constructor FormalLaurentSeries(...) around /home/yunlong/.julia/v0.6/RandomMatrices/src/FormalPowerSeries.jl:300".
Use "FormalLaurentSeries{#s60}(...) where #s60" instead.

WARNING: deprecated syntax "abstract StochasticProcess{T<:Real}" at /home/yunlong/.julia/v0.6/RandomMatrices/src/StochasticProcess.jl:7.
Use "abstract type StochasticProcess{T<:Real} end" instead.

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaLang/METADATA.jl/pull/12021
