### ISSUE TITLE
TracyWidom pdf / cdf not working

### ISSUE THREAD

**Issue by AustenLamacraft** [JuliaMath/RandomMatrices.jl#41]
`cdf(TracyWidom, 0.343)` throws `MethodError: no method matching getindex(::Void, ::Int64)
`. Also seems to be behind the [failing test](https://pkg.julialang.org/logs/RandomMatrices_0.6.log). Looks like it might be due to breaking changes in `DifferentialEquation.jl`.

**Comment by dlfivefifty** [comment]
@ChrisRackauckas I think you updated the ODE codes a while back

**Comment by dlfivefifty** [comment]
OK I'll tag a new release

**Comment by AustenLamacraft** [comment]
Thanks! In the meantime I [implemented](https://github.com/AustenLamacraft/TracyWidom.jl) Bonemann's method for direct calculation of the Fredholm determinant.

**Comment by alanedelman** [comment]
I was so excited to see Bornemann's method -- that is wonderful.  Does pdf work somewhere?
