### ISSUE TITLE
Switch to Bornemann method for Tracy-Widom distribution

### ISSUE THREAD

**Issue by AustenLamacraft** [JuliaMath/RandomMatrices.jl#43]
It seems like it would be desirable to switch the Tracy-Widom evaluation from the Painlevé to the Bornemann approach. There's an implementation here

https://github.com/AustenLamacraft/TracyWidom.jl

@andreasnoack suggested incorporating this into RandomMatrices.

**Comment by dlfivefifty** [comment]
👍 can you make a PR?

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaMath/RandomMatrices.jl/pull/44
