### ISSUE TITLE
Unable to add package to julia 1.0.3

### ISSUE THREAD

**Issue by venkatachalapathy** [JuliaMath/RandomMatrices.jl#48]
I get error message when I try to `add RandomMatrices`

`ERROR:` Unsatisfiable requirements detected for package RandomMatrices [2576dda1]:
 RandomMatrices [2576dda1] log:
 ├─possible versions are: [0.0.1-0.0.2, 0.1.0, 0.2.0-0.2.1, 0.3.0, 0.4.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.2, 0.1.0, 0.2.0-0.2.1, 0.3.0, 0.4.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left`

Any suggestions?

**Comment by dlfivefifty** [comment]
What’s your ` Pkg.status() ` ?

**Comment by venkatachalapathy** [comment]
Apologies for the delay. 

> julia> Pkg.status()
> 
>   Status C:\Users\venkatr\.julia\environments\v1.0\Project.toml
>   [2d3116d5] Bridge v0.9.0
>   [336ed68f] CSV v0.5.5
>   [159f3aea] Cairo v0.5.6
>   [35d6a980] ColorSchemes v3.1.0
>   [5ae59095] Colors v0.9.5
>   [a81c6b42] Compose v0.7.3
>   [a93c6f00] DataFrames v0.18.3
>   [7e1f9254] DiffModels v0.0.0 #master (https://github.com/DrugowitschLab/DiffModels.jl)
>   [0c46a032] DifferentialEquations v6.3.0
>   [31c24e10] Distributions v0.20.0
>   [587475ba] Flux v0.8.3
>   [186bb1d3] Fontconfig v0.2.0
>   [28b8d3ca] GR v0.40.0
>   [c91e804a] Gadfly v1.0.1
>   [a2cc645c] GraphPlot v0.3.1
>   [6218d12a] ImageMagick v0.7.4
>   [1902f260] Knet v1.2.2
>   [b964fa9f] LaTeXStrings v1.0.3
>   [093fc24a] LightGraphs v1.2.0
>   [3b7a836e] PGFPlots v3.1.1
>   [8314cec4] PGFPlotsX v0.3.5
>   [91a5bcdd] Plots v0.25.1
>   [438e738f] PyCall v1.90.0
>   [d330b81b] PyPlot v2.7.0
>   [6f49c342] RCall v0.13.2
>   [b3d1b5e5] RandomGraphs v0.0.0 [`C:\Users\venkatr\.julia\dev\RandomGraphs`]
>   [295af30f] Revise v2.1.6
>   [89279098] Shell v0.0.1
>   [bd07be1c] Winston v0.14.1

**Comment by dlfivefifty** [comment]
Maybe it’s RandomGraphs causing problems?

**Comment by venkatachalapathy** [comment]
Yes. I managed to install the package once I removed RandomGraphs, Thanks! 

Just curious. Could you tell me what the problem might have been?

**Comment by dlfivefifty** [comment]
Probably RandomGraphs.jl had a version restriction
