### ISSUE TITLE
Tracy-Widom documentation variance

### ISSUE THREAD

**Issue by lazarusA** [JuliaMath/RandomMatrices.jl#49]
It says the following:

> Tracy-Widom distribution
> The probability distribution of the normalized largest eigenvalue of a random
> matrix with iid Gaussian matrix elements of variance 1/2 and mean 0. 

but, I think that this description is only correct for $\beta = 2$ and not $\beta = 1$, in which case it should be a variance of 1 and mean zero. 
ref: https://pdfs.semanticscholar.org/df6a/a82dbd49f7646f1ca8436860ade4024246e7.pdf

> Even though, for the calculation of the largest eigenvalue normalized it doesn't change anything.

**Comment by dlfivefifty** [comment]
I’m happy to merge a PR fixing it

**Comment by lazarusA** [comment]
My bad. No need. For the standard ensembles is fine. I got confused by the Wishart case, where the variance should be taking into account in order to compare with the Tracy-Widom distribution.
