### ISSUE TITLE
Make TracyWidom order a type parameter?

### ISSUE THREAD

**Issue by dahong67** [JuliaMath/RandomMatrices.jl#54]
Hi! Thanks all for this nice package, I'm quite happily using it to evaluate the Tracy-Widom law of order 1. :)

I was wondering if it might make sense to make `TracyWidom` a parametric type with the order/index `beta` as the parameter, i.e., replace
```julia
struct TracyWidom <: ContinuousUnivariateDistribution end
```
with
```julia
struct TracyWidom{β} <: ContinuousUnivariateDistribution end
```
This seems conceptually nice, and (as far as I could tell) would also simplify some of the code by replacing `if/else` statements in the current code with dispatch (e.g., https://github.com/JuliaMath/RandomMatrices.jl/blob/master/src/densities/TracyWidom.jl#L63-L77).

If interested, I'd be happy to try it out in a pull request!

**Comment by dlfivefifty** [comment]
Why in the type? Alternatively we can do
```julia
struct TracyWidom{T} <: ContinuousUnivariateDistribution
    β::T
end
```
A good reason to prefer this is to support `BigFloat`.

**Comment by dlfivefifty** [comment]
> If interested, I'd be happy to try it out in a pull request!

Yes please!

**Comment by dahong67** [comment]
Great! I'll get started on one. :)

Making `β` a field rather than type parameter is an interesting idea, and supporting `BigFloat` is a neat point! On a related note, I'm (personally) only familiar with Tracy-Widom for `β = 1,2,4`. Do you have a reference you'd recommend for other `β`'s being used?

One advantage of putting `β` in the type is that we could then dispatch on it.

**Comment by dlfivefifty** [comment]
Dumitriu and Edelman  have a lot of papers on general β. The easiest construction is via a tridiagonal matrix with χ distributed off diagonal entries

I can’t see why one would need dispatch, an if statement will be just as convenient

**Comment by dahong67** [comment]
Ah right, thanks so much for the pointer! I also thought some more and agree with you that there is not really a need for dispatch here.

I'll start the pull request once I get some free time - hopefully this weekend!
