### ISSUE TITLE
Is this package not maintained anymore?

### ISSUE THREAD

**Issue by jamblejoe** [JuliaMath/RandomMatrices.jl#58]
Looking through the source code, documentation and the latest commits/merges, this project seems a bit abondend. Am I wrong?

EDIT: Just to clarify, I was looking for a central package dealing with random matrix generation and was very happy, when I discovered this. It would be a pitty to not maintain such good work here!

**Comment by dlfivefifty** [comment]
It's being maintained, just not developed. It would be fantastic for it to get some attention, and I'll quickly merge PRs

**Comment by dlfivefifty** [comment]
(The code was originally written in 2013 by @jiahao so almost everything could be improved for Julia v1.0)

**Comment by jamblejoe** [comment]
ok! I guess @jiahao is not around anymore, contributing to this package? I would be happy to contribute, but my knowledge of Julia is mediocre, as it is of the generation of random matrices.
