### ISSUE TITLE
Move to JuliaLinearAlgebra?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaMath/RandomMatrices.jl#60]
Perhaps the JuliaLinearAlgebra org is a better home for this package.  Is it ok if I transfer?

**Comment by dlfivefifty** [comment]
JuliaMatrices would make more sense. Even better would be something like JuliaProbability, if it exists

**Comment by ViralBShah** [comment]
Yes JuliaMatrices seems best for now.
